SELECT DISTINCT
	e.NOME as CURSO, 
	d.NOME as TURMA,
	b.NOME as ALUNO,
	b.CPF,
	b.RG,
	b.CEP,
	b.LOGRADOURO,
	ISNULL(b.NUMERO, '') AS NUMERO,
	h.DESCRICAO AS BAIRRO,
	i.DESCRICAO AS CIDADE,
	ISNULL(j.SIGLA, '') AS SIGLA,
	ISNULL(b.CONTATO1, '') as CONTATO1,
	ISNULL(b.CONTATO2, '') as CONTATO2,
	ISNULL(b.CONTATO3, '') as CONTATO3,
	ISNULL(b.COMPLEMENTO, '') as COMPLEMENTO,
	ISNULL(g.NOMEFANTASIA, '') as ESCOLA,
	ISNULL(f.CURSO_ANT_ANO, '') as ANO_CONCLUSAO,
	CASE 
		WHEN (
			SELECT COUNT(a1.CODIGO) FROM SONATA.SOPHIA.SOPHIA.MATRICULA a1
			WHERE a1.FISICA = b.CODIGO AND a1.CURSO = e.PRODUTO
			GROUP BY a1.FISICA, a1.CURSO
			
		) > 1 THEN -- AGRUPA PELA PESSOA E PELO CURSO, E SE TIVER MAIS QUE UM CURSO
			CASE
				WHEN(
					SELECT COUNT(*) FROM(
						SELECT COUNT(c.ORDEM) as asd FROM SONATA.SOPHIA.SOPHIA.MATRICULA a1
						INNER JOIN SONATA.SOPHIA.SOPHIA.TURMAS b1 ON b1.CODIGO = a1.TURMA_REGULAR
						INNER JOIN SONATA.SOPHIA.SOPHIA.SERIE c ON c.CODIGO = b1.SERIE
						WHERE FISICA = b.CODIGO AND a1.CURSO = e.PRODUTO
						GROUP BY FISICA, a1.CURSO, c.ORDEM
					) a 
				) = 1 THEN
				'Ingressantes com reprovação'
			ELSE
				'--'
			END
		ELSE
			'Ingressantes'
	END REGULARES,
	(
		SELECT MIN(YEAR(b1.INICIO)) FROM SONATA.SOPHIA.SOPHIA.MATRICULA a1
		INNER JOIN SONATA.SOPHIA.SOPHIA.TURMAS b1 ON b1.CODIGO = a1.TURMA_REGULAR
		INNER JOIN SONATA.SOPHIA.SOPHIA.SERIE c ON c.CODIGO = b1.SERIE
		WHERE FISICA = b.CODIGO AND a1.CURSO = e.PRODUTO
	) as ANO_DE_INGRESSO
FROM SONATA.SOPHIA.SOPHIA.MATRICULA a
INNER JOIN SONATA.SOPHIA.SOPHIA.FISICA b ON b.CODIGO = a.FISICA
INNER JOIN SONATA.SOPHIA.SOPHIA.PERIODOS c ON c.CODIGO = a.PERIODO 
INNER JOIN SONATA.SOPHIA.SOPHIA.TURMAS d ON d.CODIGO = a.TURMA_REGULAR
INNER JOIN SONATA.SOPHIA.SOPHIA.CURSOS e ON e.PRODUTO = d.CURSO
INNER JOIN SONATA.SOPHIA.SOPHIA.INSCRICAO f ON f.FISICA = b.CODIGO
LEFT JOIN SONATA.SOPHIA.SOPHIA.JURIDICA g ON g.CODIGO = f.CURSO_ANT_ESCOLA
LEFT JOIN SONATA.SOPHIA.SOPHIA.BAIRROS h ON h.CODIGO = b.BAIRRO
LEFT JOIN SONATA.SOPHIA.SOPHIA.CIDADES i ON i.CODIGO = b.CIDADE
LEFT JOIN SONATA.SOPHIA.SOPHIA.UNIDADE_FEDERATIVA j ON j.CODIGO = i.UF
WHERE c.CODIGO = 120 AND a.TURMA_REGULAR in(
	--2526,	2529,	2582,	2589,	2590,
	--2530,	2531,	2568,	2536,	2535,	2581
	2400,2425,2502,2398,2366,2401,2369 
) --AND f.CURSO_ANT_ANO IS NULL
ORDER BY e.NOME,d.NOME,b.NOME
------------------------------------------------------------------------
------------------------------------------------------------------------

SELECT a.NOME, COUNT(c.DISCIPLINA), AVG(c.MEDIA_FINAL)
FROM SONATA.SOPHIA.SOPHIA.FISICA a
INNER JOIN SONATA.SOPHIA.SOPHIA.MATRICULA b ON b.FISICA = a.CODIGO AND b.PERIODO = 120-- AND b.STATUS = 0
INNER JOIN SONATA.SOPHIA.SOPHIA.ACADEMIC c ON c.MATRICULA = b.CODIGO
WHERE replace(replace(a.CPF,'-',''),'.','') in
('39123334835',
'38222244809',
'35783329843',
'33589644850',
'33742963864',
'33729164848',
'37795203892',
'35322487867',
'21309589828',
'22536706850',
'35958891855',
'32576858821',
'37158892840',
'39824760890',
'40238213811',
'36280096858',
'39733658812',
'23439330818',
'42304017878',
'36631569826',
'35693539822',
'21963197836',
'36468352819',
'21867008831',
'06749068960',
'41322539880',
'39595222828',
'34018730837',
'38751001829',
'40090326857'
)
GROUP BY  a.NOME
ORDER BY a.nome
------------------------------------------------------------------------
------------------------------------------------------------------------
SELECT * FROM SONATA.SOPHIA.SOPHIA.FORMAS_CONTATO
SELECT * FROM SONATA.SOPHIA.SOPHIA.INSCRICAO WHERE FISICA = 16083
SELECT * FROM SONATA.SOPHIA.SOPHIA.CURRICULO WHERE CODIGO = 10154
SELECT * FROM SOPHIA.JURIDICA WHERE CODIGO = 2651
SELECT * FROM SOPHIA.MATRICULA WHERE FISICA = 13548
SELECT * FROM SOPHIA.FISICA WHERE NOME LIKE 'Kaio%Thauan%Vieira%Dantas'
SELECT * FROM SOPHIA.SERIE WHERE CODIGO IN(241, 628)
SELECT * FROM SONATA.SOPHIA.SOPHIA.TURMAS WHERE PERIODO = 120 ORDER BY NOME
SELECT * FROM SOPHIA.BAIRROS
SELECT * FROM SOPHIA.CIDADES
SELECT * FROM SOPHIA.UNIDADE_FEDERATIVA
SELECT * FROM SONATA.SOPHIA.SOPHIA.MATRICULA
SELECT * FROM SONATA.SOPHIA.SOPHIA.SERIE
SELECT * FROM SONATA.SOPHIA.SOPHIA.CURRICULO
SELECT * FROM SONATA.SOPHIA.SOPHIA.ACADEMIC
SELECT * FROM SONATA.SOPHIA.SOPHIA.CURSOS WHERE PRODUTO in(23,26)

SELECT MIN(YEAR(b1.INICIO)) FROM SONATA.SOPHIA.SOPHIA.MATRICULA a1
INNER JOIN SONATA.SOPHIA.SOPHIA.TURMAS b1 ON b1.CODIGO = a1.TURMA_REGULAR
INNER JOIN SONATA.SOPHIA.SOPHIA.SERIE c ON c.CODIGO = b1.SERIE
WHERE FISICA = 13548 AND a1.CURSO = 43
GROUP BY FISICA, a1.CURSO, c.ORDEM

SELECT COUNT(*) FROM(
	SELECT COUNT(b1.SERIE) as asd FROM SONATA.SOPHIA.SOPHIA.MATRICULA a1
	INNER JOIN SONATA.SOPHIA.SOPHIA.TURMAS b1 ON b1.CODIGO = a1.TURMA_REGULAR
	INNER JOIN SONATA.SOPHIA.SOPHIA.SERIE c ON c.CODIGO = b1.SERIE
	WHERE FISICA = 13548 AND a1.CURSO = 43
	GROUP BY FISICA, a1.CURSO, b1.SERIE
) a
			
[SOPHIA.FISICA]
[SOPHIA.INSCRICAO]

SELECT COUNT(CODIGO) FROM SONATA.SOPHIA.SOPHIA.MATRICULA WHERE FISICA = 13548 AND CURSO = 43
GROUP BY FISICA, CURSO

------------------ EAD ------------------
SELECT B.* FROM 
SONATA.SOPHIA.SOPHIA.MATRICULA A 
INNER JOIN SONATA.SOPHIA.SOPHIA.FISICA B ON B.CODIGO = A.FISICA 
INNER JOIN SONATA.SOPHIA.SOPHIA.CURSOS C ON C.PRODUTO = A.CURSO
INNER JOIN SONATA.SOPHIA.SOPHIA.SERIE D ON D.CODIGO = A.SERIE
INNER JOIN SONATA.SOPHIA.SOPHIA.CURRICULO E ON E.CODIGO = D.CURRICULO
WHERE A.PERIODO = 125 AND A.STATUS IN(0, 5)


SELECT B.* FROM 
SONATA.SOPHIA.SOPHIA.MATRICULA A 
INNER JOIN SONATA.SOPHIA.SOPHIA.FISICA B ON B.CODIGO = A.FISICA 
INNER JOIN SONATA.SOPHIA.SOPHIA.ACADEMIC C ON C.MATRICULA = A.CODIGO
INNER JOIN SONATA.SOPHIA.SOPHIA.CURSOS D ON D.PRODUTO = A.CURSO
INNER JOIN SONATA.SOPHIA.SOPHIA.DISCIPLINAS E ON E.CODIGO = C.DISCIPLINA
WHERE A.PERIODO = 125 AND A.STATUS IN(0, 5) and D.PRODUTO not in(23,26)

select d.codext as usuario, d.senha, Substring(d.nome,1,charindex(' ',d.nome,1)) as firstname,
ltrim(replace(d.nome,Substring(d.nome,1,charindex(' ',d.nome,1)),'')) as lastname, d.email, 
g.nome as nomedisciplina, E.NOME
from SONATA.SOPHIA.sophia.ACADEMIC a 
inner join SONATA.SOPHIA.sophia.MATRICULA b on a.matricula = b.codigo
inner join SONATA.SOPHIA.sophia.PERIODOS c on c.codigo = b.periodo
inner join SONATA.SOPHIA.sophia.FISICA d on b.fisica = d.codigo
inner join SONATA.SOPHIA.sophia.CURSOS e on b.curso = e.produto
inner join SONATA.SOPHIA.sophia.TURMAS f on a.turma = f.codigo
inner join SONATA.SOPHIA.sophia.DISCIPLINAS g on a.DISCIPLINA = g.codigo
where c.codigo = 125 and b.status = 0 and e.PRODUTO not in(23,26) --Tirando cursos do Colegio, matriculas com status ativo e do semestre 2012/1
order by d.nome
