SELECT 
	b.CODIGO AS TITULO, b.DATA_VCTO, d.DESCRICAO,  a.CODEXT AS RA, a.NOME, a.EMAIL, a.CONTATO1, a.CONTATO2, a.CONTATO3
FROM SOPHIA.FISICA a
INNER JOIN SOPHIA.TITULOS b ON b.CODPF = a.CODIGO
INNER JOIN SOPHIA.MOVFIN c ON c.TITULO = b.CODIGO
INNER JOIN SOPHIA.PLANOCONTAS d ON d.CODIGO  = c.CLASSIFICACAO
WHERE 
	b.DATA_VCTO 
		BETWEEN '2015-07-01' AND '2015-07-31' AND
	d.DESCRICAO LIKE '%rematricula%' AND
	a.CODEXT COLLATE SQL_Latin1_General_CP850_CI_AI  in (
	
		SELECT 
			desra COLLATE SQL_Latin1_General_CP850_CI_AI 
		FROM 
			SATURN.FIT_NEW.dbo.tb_solicitacao_rematricula	
		WHERE 
			idperiodo = 128
	) AND
	b.RECEBIDO = 0
GROUP BY
	b.CODIGO , b.DATA_VCTO, d.DESCRICAO,  a.CODEXT , a.NOME, a.EMAIL, a.CONTATO1, a.CONTATO2, a.CONTATO3
ORDER BY NOME
