

WITH tb_relatorio
	(NOME, EMAIL, CONTATO1, CONTATO2, CONTATO3, TURMA, CURSO)
AS(
	SELECT 
		b.NOME, b.EMAIL, 
		CASE WHEN b.FORMACONTATO1 = 2 THEN
			b.CONTATO1
		END AS CONTATO1,
		CASE WHEN b.FORMACONTATO2 = 2 THEN
			b.CONTATO2
		END AS CONTATO3,
		CASE WHEN b.FORMACONTATO3 = 2 THEN
			b.CONTATO3
		END AS CONTATO3,
		c.NOME AS TURMA,
		d.NOME as CURSO 
	FROM SOPHIA.MATRICULA a
	INNER JOIN SOPHIA.FISICA b ON b.CODIGO = a.FISICA
	INNER JOIN SOPHIA.TURMAS c ON C.CODIGO = a.TURMA_REGULAR
	INNER JOIN SOPHIA.CURSOS d ON d.PRODUTO = c.CURSO
	INNER JOIN SOPHIA.NIVEL e ON e.CODIGO = d.NIVEL
	WHERE a.STATUS in(0,5) AND e.CODIGO in(1, 2, 4) AND c.PERIODO = 125
)

SELECT 
	NOME, EMAIL,
	REPLACE(REPLACE(ISNULL(CONTATO1,ISNULL(CONTATO2, ISNULL(CONTATO3, NULL))), ' ', ''), '-', '') AS CELULAR,
	TURMA, CURSO
FROM tb_relatorio
ORDER BY CURSO, TURMA, NOME