
SELECT * FROM SOPHIA.BAIRROS
SELECT * FROM SOPHIA.PERIODOS
SELECT * FROM SOPHIA.NIVEL

SELECT 
	d.NOME as Turma,
	a.CODEXT as RA,
	a.NOME as Nome,
	c.DESCRICAO as Bairro,
	a.CEP
FROM SOPHIA.FISICA a
INNER JOIN SOPHIA.MATRICULA b ON b.FISICA = a.CODIGO
LEFT JOIN SOPHIA.BAIRROS c ON c.CODIGO = a.BAIRRO
INNER JOIN SOPHIA.TURMAS d ON d.CODIGO = b.TURMA_REGULAR
INNER JOIN SOPHIA.CURSOS e ON e.PRODUTO = d.CURSO
WHERE d.PERIODO = 127 AND b.STATUS in (0, 5) AND e.NIVEL in (1, 2) AND d.NOME NOT LIKE 'CDT%' AND d.NOME NOT LIKE 'TESTE%' AND (
		SELECT COUNT(*) FROM SophiA.MATRICULA
		WHERE FISICA = a.CODIGO  AND STATUS in(0, 5)
	) = 1
GROUP BY
	a.CODEXT,
	a.NOME,
	c.DESCRICAO,
	a.CODIGO,
	d.NOME,
	a.CEP
ORDER BY d.NOME, a.NOME
