
SELECT 
	b.CODEXT,
	b.NOME,
	d.CODIGO  AS TITULO,
	e.DESCRICAO,
	d.RECEBIDO,
	d.DATA_BAIXA
FROM SATURN.FIT_NEW.dbo.tb_solicitacao_rematricula a
INNER JOIN SONATA.SOPHIA.SOPHIA.FISICA b ON b.CODEXT COLLATE  SQL_Latin1_General_CP850_CI_AI =  a.desra COLLATE  SQL_Latin1_General_CP850_CI_AI
INNER JOIN SONATA.SOPHIA.SOPHIA.MATRICULA c ON c.FISICA = b.CODIGO
INNER JOIN SONATA.SOPHIA.SOPHIA.TITULOS d ON d.CODPF = b.CODIGO
INNER JOIN SONATA.SOPHIA.SOPHIA.MOVFIN e ON e.TITULO = d.CODIGO
WHERE 
	a.idperiodo = 128 AND
	c.STATUS = 0 AND
	e.DESCRICAO LIKE 'REmatr%' AND
	d.DATA_VCTO > '2015-07-01' AND
	d.RECEBIDO <> 2 AND
	d.DATA_BAIXA < '2015-06-01'
ORDER BY b.NOME
	
SELECT * FROM SONATA.SOPHIA.SOPHIA.MOVFIN WHERE TITULO = 761749
SELECT * FROM SONATA.SOPHIA.SOPHIA.TITULOS