SELECT 
	d.NOME AS TURMA,
	a.CODEXT as RA,
	a.NOME,
	f.destipomatr,
	g.dessituacao,
	e.NOME as TURMA_REGULAR
FROM SOPHIA.FISICA a
INNER JOIN SophiA.MATRICULA b on b.FISICA = a.CODIGO
INNER JOIN SOPHIA.ACADEMIC c ON c.MATRICULA = b.CODIGO
INNER JOIN SOPHIA.TURMAS d ON d.CODIGO = c.TURMA
INNER JOIN SOPHIA.TURMAS e ON e.CODIGO = b.TURMA_REGULAR
LEFT JOIN dbo.tb_academic_tipomatr f ON f.idtipomatr = c.TIPO_MATR
LEFT JOIN dbo.tb_academic_situacao g ON g.idsituacao = c.SITUACAO
WHERE b.STATUS = 0 AND c.DISCIPLINA = 1536 AND d.TURNO = 1 AND d.PERIODO = 128
ORDER BY d.NOME, a.NOME