SELECT 
	d.NOME AS TURMA,
	a.CODEXT AS RA, 
	a.NOME,
	COUNT(*) AS QTDE_REPROVACOES
FROM SOPHIA.FISICA a 
INNER JOIN SOPHIA.MATRICULA b ON b.FISICA = A.CODIGO
INNEr JOIN SOPHIA.ACADEMIC C on	 C.MATRICULA = b.CODIGO
INNER JOIN SOPHIA.TURMAS d on d.CODIGO = c.TURMA
WHERE 
	d.PERIODO = 127 AND C.SITUACAO = 2 AND b.STATUS in(0, 5)
GROUP BY
	a.CODEXT,
	a.NOME,
	d.NOME
HAVING COUNT(*) >= 4
ORDER BY
	d.NOME,
	a.NOME
	

SELECT * FROM SOPHIA.ACADEMIC

