


SELECT 
	a.CODIGO,
	c.NOME as TURMA,
	a.CODEXT as RA,
	a.NOME,
	a.EMAIL,
	ISNULL(a.CONTATO1, '') as CONTATO1,
	ISNULL(a.CONTATO2, '') as CONTATO1,
	ISNULL(a.CONTATO3, '') as CONTATO1
FROM SOPHIA.FISICA a
INNER JOIN SOPHIA.MATRICULA b ON b.FISICA = a.CODIGO
INNER JOIN SOPHIA.TURMAS c ON c.CODIGO = b.TURMA_REGULAR
LEFT JOIN (
	SELECT a.CODIGO FROM SOPHIA.FISICA a
	INNER JOIN SOPHIA.MATRICULA b ON b.FISICA = a.CODIGO
	INNER JOIN SOPHIA.TURMAS c ON c.CODIGO = b.TURMA_REGULAR
	WHERE c.CFG_ACAD = 1 AND c.PERIODO = 128
) d ON d.CODIGO = a.CODIGO
WHERE 
	b.STATUS in(0,5) AND 
	c.CFG_ACAD = 1 AND 
	c.PERIODO = 127 AND
	d.CODIGO IS NULL
ORDER BY 
	c.NOME,
	a.NOME


