SELECT DISTINCT 
	c.AULA,
	b.NOME as TURMA,
	f.NOME as DISCIPLINA,
	a.MATRICULA,
	e.NOME,
	c.FALTA,
	a.TIPO_MATR,
	a.FALTAS1,
	a.FALTAS2,
	a.FALTAS3,
	a.FALTAS4,
	a.PERC_FALTAS,
	a.SITUACAO
FROM SOPHIA.ACADEMIC a
INNER JOIN SOPHIA.TURMAS b ON b.CODIGO = a.TURMA
INNER JOIN SOPHIA.LISTA_CHAM_ALUNOS c ON c.MATRICULA = a.MATRICULA
INNER JOIN SOPHIA.MATRICULA d ON d.CODIGO = a.MATRICULA
INNER JOIN SOPHIA.FISICA e ON e.CODIGO = d.FISICA
INNER JOIN SOPHIA.DISCIPLINAS f ON f.CODIGO = a.DISCIPLINA
WHERE 
	b.PERIODO = 127 AND
	--c.FALTA = 1 AND
	a.TIPO_MATR  IN (
		4, --  Dispensa médica
		5--, -- Dispensa
		--8, -- Trancada
		--9, -- Impedida
		--14, -- Cancelada
		--17 -- Mat. Cancelada
	) AND(
	
		a.FALTAS1 <> 0 OR a.FALTAS2 <> 0 OR a.FALTAS3 <> 0 OR a.FALTAS4 <> 0 
	)
ORDER BY a.MATRICULA, f.NOME



SELECT * FROM SophiA.LISTA_CHAM
SELECT * FROM SOPHIA.LISTA_CHAM_ALUNOS
SELECT  * FROM SOPHIA.ACADEMIC WHERE MATRICULA = 38338
 

SELECT TIPO_MATR, * FROM SOPHIA.ACADEMIC
WHERE MATRICULA IN (
	SELECT DISTINCT 
		a.MATRICULA
	FROM SOPHIA.ACADEMIC a
	INNER JOIN SOPHIA.TURMAS b ON b.CODIGO = a.TURMA
	INNER JOIN SOPHIA.LISTA_CHAM_ALUNOS c ON c.MATRICULA = a.MATRICULA
	INNER JOIN SOPHIA.MATRICULA d ON d.CODIGO = a.MATRICULA
	INNER JOIN SOPHIA.FISICA e ON e.CODIGO = d.FISICA
	INNER JOIN SOPHIA.DISCIPLINAS f ON f.CODIGO = a.DISCIPLINA
	WHERE 
		b.PERIODO = 127 AND
		c.FALTA = 1 AND
		a.TIPO_MATR  IN (
			4, --  Dispensa médica
			5, -- Dispensa
			8, -- Trancada
			9, -- Impedida
			14, -- Cancelada
			17 -- Mat. Cancelada
		)
)

BEGIN TRAN
UPDATE SOPHIA.LISTA_CHAM_ALUNOS
SET FALTA = 0
FROM SOPHIA.ACADEMIC a
INNER JOIN SOPHIA.TURMAS b ON b.CODIGO = a.TURMA
INNER JOIN SOPHIA.LISTA_CHAM_ALUNOS c ON c.MATRICULA = a.MATRICULA
INNER JOIN SOPHIA.MATRICULA d ON d.CODIGO = a.MATRICULA
INNER JOIN SOPHIA.FISICA e ON e.CODIGO = d.FISICA
INNER JOIN SOPHIA.DISCIPLINAS f ON f.CODIGO = a.DISCIPLINA
WHERE 
	b.PERIODO = 127 AND
	c.FALTA = 1 AND
	a.TIPO_MATR  IN (
		4, --  Dispensa médica
		5, -- Dispensa
		8, -- Trancada
		9, -- Impedida
		14, -- Cancelada
		17 -- Mat. Cancelada
	)
ORDER BY a.MATRICULA, f.NOME


COMMIT
------------------------------------------------------
------------------------------------------------------
UPDATE SOPHIA.ACADEMIC 
SET 
	FALTAS1 = 0,
	FALTAS2 = 0,
	FALTAS3 = 0,
	FALTAS4 = 0,
	PERC_FALTAS = 0.0000
FROM SOPHIA.ACADEMIC a
INNER JOIN SOPHIA.TURMAS b ON b.CODIGO = a.TURMA
INNER JOIN SOPHIA.LISTA_CHAM_ALUNOS c ON c.MATRICULA = a.MATRICULA
INNER JOIN SOPHIA.MATRICULA d ON d.CODIGO = a.MATRICULA
INNER JOIN SOPHIA.FISICA e ON e.CODIGO = d.FISICA
INNER JOIN SOPHIA.DISCIPLINAS f ON f.CODIGO = a.DISCIPLINA
WHERE 
	b.PERIODO = 127 AND
	--c.FALTA = 1 AND
	a.TIPO_MATR  IN (
		4, --  Dispensa médica
		5--, -- Dispensa
	) AND(
	
		a.FALTAS1 <> 0 OR a.FALTAS2 <> 0 OR a.FALTAS3 <> 0 OR a.FALTAS4 <> 0 
	)
